on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run all tests
        uses: dagger/dagger-for-github@v2
        with:
          args: do test --log-format plain
