on:
  push:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run all tests
        uses: dagger/dagger-for-github@v2
        with:
          cmds: do test --log-format plain
