on:
  push

jobs:
  unit-test:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        uses: dagger/dagger-for-github@v2
        with:
          args: do unit --log-format plain
