on:
  push

jobs:
  unit-test:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dagger
        uses: dagger/dagger-for-github@v2
        with:
          install-only: true
      - name: Run unit tests
        run: dagger do unit --log-format plain
